from setuptools import setup
import re


name = "steelconnection"
description = "Simplify access to the Riverbed SteelConnect REST API."
version = "1.1.7"
author = "Greg Mueller"
author_email = "steelconnection@grelleum.com"
copyright = "Copyright 2018-2020 Greg Mueller"
license = "MIT"
project_home = "https://github.com/grelleum/SteelConnection"
documentation = "https://steelconnection.readthedocs.io/"


info = {
    "name": name,
    "description": description,
    "version": version,
    "author": author,
    "author_email": author_email,
    "license": license,
    "url": project_home,
    "long_description_content_type": "text/x-rst",
    "install_requires": ["requests>=2.12.1"],
    "keywords": ["SteelConnect", "REST", "API", "Riverbed", "Grelleum"],
    "packages": ["steelconnection"],
    "classifiers": [
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
}


# Generate 'about.py' file.
about = '''"""
about.py

Do not edit: This file is automatically generated by setup.py.
"""

name = "{name}"
description = "{description}"
version = "{version}"
author = "{author}"
author_email = "{author_email}"
copyright = "{copyright}"
license = "{license}"
project_home = "{project_home}"
documentation = "{documentation}"
'''

about = about.format(
    name=name,
    description=description,
    version=version,
    author=author,
    author_email=author_email,
    copyright=copyright,
    license=license,
    project_home=project_home,
    documentation=documentation,
)

with open(name + "/about.py", "wt") as fh:
    fh.write(about)


def read_file_and_update_version(filename):
    """Replace version number within a file."""
    old_version = re.compile(r"   version \d+\.[\d\.]+[a-z]?")
    new_version = "   version {}".format(version)
    with open(filename, "rt") as fh:
        contents = fh.read()
    contents = old_version.sub(new_version, contents)
    with open(filename, "wt") as fh:
        fh.write(contents)
    return contents


print("VERSION:", info["version"])

read_file_and_update_version("docs/index.rst")
long_description = read_file_and_update_version("README.rst")
info["long_description"] = long_description

setup(**info)
