
"""
about.py

Do not edit: This file is automatically generated by setup.py.
"""

name = {name}
description = {description}
version = {version}
author = {author}
author_email = {author_email}
copyright = {copyright}
license = {license}
project_home = {project_home}
documentation = {documentation}
